/* tslint:disable: object-literal-key-quotes */
export const menulist = [
    {
        'title': '首页',
        'type': 'menu',
        'path': '/flight',
        'name': 'homepage',
        'key': 'homepage',
        'id': 100,
        'parentId': 0,
        'isParentMenu': false,
        'icon': 'homepage',
        'children': null,
    },
    {
        'title': '企业设置',
        'type': 'subMenu',
        'path': '',
        'name': 'company_config',
        'key': 'company_config',
        'id': 94,
        'parentId': 0,
        'isParentMenu': true,
        'icon': 'orgStructure',
        'children': [
            {
                'title': '组织架构',
                'type': 'subMenu',
                'path': '',
                'name': 'orgStructure',
                'key': 'orgStructure',
                'id': 81,
                'parentId': 94,
                'isParentMenu': true,
                'icon': null,
                'children': [
                    {
                        'title': '组织架构',
                        'type': 'menu',
                        'path': '/orgStructure/organization',
                        'name': 'orgStructure_organization',
                        'key': 'orgStructure_organization',
                        'id': 11,
                        'parentId': 81,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '人员信息',
                        'type': 'menu',
                        'path': '/orgStructure/employeeList',
                        'name': 'orgStructure_employeeList',
                        'key': 'orgStructure_employeeList',
                        'id': 105,
                        'parentId': 81,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '公司职级管理',
                        'type': 'menu',
                        'path': '/orgStructure/position',
                        'name': 'orgStructure_position',
                        'key': 'orgStructure_position',
                        'id': 12,
                        'parentId': 81,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                        'canChangeCorp': true,
                    },
                    {
                        'title': '代订权限',
                        'type': 'menu',
                        'path': '/orgStructure/bookingPermission',
                        'name': 'orgStructure_bookingPermission',
                        'key': 'orgStructure_bookingPermission',
                        'id': 109,
                        'parentId': 81,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                        'canChangeCorp': true,
                    },
                    {
                        'title': '公司角色管理',
                        'type': 'menu',
                        'path': '/permissionConfig/roleConfig',
                        'name': 'permissionConfig_roleConfig',
                        'key': 'permissionConfig_roleConfig',
                        'id': 28,
                        'parentId': 81,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                        'canChangeCorp': true,
                    },
                ],
            },
            {
                'title': '职级差标管理',
                'type': 'subMenu',
                'path': '',
                'name': 'travelstandard_config',
                'key': 'travelstandard_config',
                'id': 82,
                'parentId': 94,
                'isParentMenu': true,
                'icon': null,
                'children': [
                    {
                        'title': '国内机票差标',
                        'type': 'menu',
                        'path': '/travelstandard/dom',
                        'name': 'travelstandard_dom',
                        'key': 'travelstandard_dom',
                        'id': 17,
                        'parentId': 82,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                        'canChangeCorp': true,
                    },
                    {
                        'title': '火车票差标',
                        'type': 'menu',
                        'path': '/travelstandard/train',
                        'name': 'travelstandard_train',
                        'key': 'travelstandard_train',
                        'id': 20,
                        'parentId': 82,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                        'canChangeCorp': true,
                    },
                    {
                        'title': '酒店差标',
                        'type': 'menu',
                        'path': '/travelstandard/hotel',
                        'name': 'travelstandard_hotel',
                        'key': 'travelstandard_hotel',
                        'id': 19,
                        'parentId': 82,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                        'canChangeCorp': true,
                    },
                ],
            },
            {
                'title': '消息发送配置',
                'type': 'menu',
                'path': '/companyMsgSet/sendMsgSet',
                'name': 'companyMsgSet_sendMsgSet',
                'key': 'companyMsgSet_sendMsgSet',
                'id': 116,
                'parentId': 94,
                'isParentMenu': false,
                'icon': null,
                'children': null,
                'canChangeCorp': true,
            },
            {
                'title': '出差申请审批配置',
                'type': 'subMenu',
                'path': '',
                'name': 'travelApplication',
                'key': 'travelApplication',
                'id': 106,
                'parentId': 94,
                'isParentMenu': true,
                'icon': null,
                'children': [
                    {
                        'title': '审批配置',
                        'type': 'menu',
                        'path': '/travelApplication/approvalconfig',
                        'name': 'travelApplication_approvalconfig',
                        'key': 'travelApplication_approvalconfig',
                        'id': 16,
                        'parentId': 106,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                        'canChangeCorp': true,
                    },
                ],
            },
        ],
    },
    {
        'title': '服务商管理',
        'type': 'subMenu',
        'path': '',
        'name': 'serviceManager',
        'key': 'serviceManager',
        'id': 83,
        'parentId': 0,
        'isParentMenu': true,
        'icon': 'serviceManager',
        'children': [
            {
                'title': '服务商管理',
                'type': 'menu',
                'path': '/serviceManager/serviceList',
                'name': 'serviceManager_serviceList',
                'key': 'serviceManager_serviceList',
                'id': 56,
                'parentId': 83,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '\r\n企业与服务商',
                'type': 'menu',
                'path': '/serviceManager/companyAndService',
                'name': 'serviceManager_companyAndService',
                'key': 'serviceManager_companyAndService',
                'id': 78,
                'parentId': 83,
                'isParentMenu': false,
                'icon': null,
                'children': null,
                'canChangeCorp': true,
            },
        ],
    },
    {
        'title': '企业服务商管理',
        'type': 'menu',
        'path': '/suppliers/suppliersList',
        'name': 'suppliers_suppliersList',
        'key': 'suppliers_suppliersList',
        'id': 101,
        'parentId': 0,
        'isParentMenu': false,
        'icon': 'suppliersList',
        'children': null,
    },
    {
        'title': '账号管理',
        'type': 'subMenu',
        'path': '',
        'name': 'accountManager',
        'key': 'accountManager',
        'id': 84,
        'parentId': 0,
        'isParentMenu': true,
        'icon': 'bgPermissionConfig',
        'children': [
            {
                'title': '用户账号管理',
                'type': 'menu',
                'path': '/accountManager/accountList',
                'name': 'accountManager_accountList',
                'key': 'accountManager_accountList',
                'id': 75,
                'parentId': 84,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '运营账号管理',
                'type': 'subMenu',
                'path': '',
                'name': 'bgPermissionConfig',
                'key': 'bgPermissionConfig',
                'id': 85,
                'parentId': 84,
                'isParentMenu': true,
                'icon': null,
                'children': [
                    {
                        'title': '运营角色管理',
                        'type': 'menu',
                        'path': '/bgPermissionConfig/roleConfig',
                        'name': 'bgPermissionConfig_roleConfig',
                        'key': 'bgPermissionConfig_roleConfig',
                        'id': 32,
                        'parentId': 85,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '运营账号管理',
                        'type': 'menu',
                        'path': '/bgPermissionConfig/accountConfig',
                        'name': 'bgPermissionConfig_accountConfig',
                        'key': 'bgPermissionConfig_accountConfig',
                        'id': 33,
                        'parentId': 85,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                ],
            },
        ],
    },
    {
        'title': '系统管理',
        'type': 'subMenu',
        'path': '',
        'name': 'systemManager',
        'key': 'systemManager',
        'id': 86,
        'parentId': 0,
        'isParentMenu': true,
        'icon': 'systemManager',
        'children': [
            {
                'title': '系统设置',
                'type': 'menu',
                'path': '/systemManager/systemSetting',
                'name': 'systemManager_systemSetting',
                'key': 'systemManager_systemSetting',
                'id': 79,
                'parentId': 86,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '评价项管理',
                'type': 'menu',
                'path': '/systemManager/evaluationManager',
                'name': 'satisfactionManagement',
                'key': 'satisfactionManagement',
                'id': 103,
                'parentId': 86,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '消息公告管理',
                'type': 'menu',
                'path': '/notices/messages',
                'name': 'notices_messages',
                'key': 'notices_messages',
                'id': 35,
                'parentId': 86,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '系统广告管理',
                'type': 'menu',
                'path': '/ads/list',
                'name': 'ads_list',
                'key': 'ads_list',
                'id': 37,
                'parentId': 86,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
        ],
    },
    {
        'title': '对账',
        'type': 'subMenu',
        'path': '',
        'name': 'reconciliation',
        'key': 'reconciliation',
        'id': 87,
        'parentId': 0,
        'isParentMenu': true,
        'icon': 'reconciliation',
        'children': [
            {
                'title': '运营对账',
                'type': 'menu',
                'path': '/reconciliation/list',
                'name': 'bill_reconciliation',
                'key': 'bill_reconciliation',
                'id': 110,
                'parentId': 87,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '企业对账',
                'type': 'menu',
                'path': '/receptReconciliation/list',
                'name': 'recept_reconciliation',
                'key': 'recept_reconciliation',
                'id': 95,
                'parentId': 87,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
        ],
    },
    {
        'title': '日志管理',
        'type': 'subMenu',
        'path': '',
        'name': 'logManage',
        'key': 'logManage',
        'id': 88,
        'parentId': 0,
        'isParentMenu': true,
        'icon': 'logManage',
        'children': [
            {
                'title': '操作日志管理',
                'type': 'menu',
                'path': '/log/log',
                'name': 'log_log',
                'key': 'log_log',
                'id': 34,
                'parentId': 88,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '系统短信邮件发送记录',
                'type': 'menu',
                'path': '/system/email',
                'name': 'system_email',
                'key': 'system_email',
                'id': 36,
                'parentId': 88,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
        ],
    },
    {
        'title': '业务管理',
        'type': 'subMenu',
        'path': '',
        'name': 'businessManagement',
        'key': 'businessManagement',
        'id': 89,
        'parentId': 0,
        'isParentMenu': true,
        'icon': 'BusinessManagement',
        'children': [
            {
                'title': '订单管理',
                'type': 'subMenu',
                'path': '',
                'name': 'orderManagement',
                'key': 'orderManagement',
                'id': 90,
                'parentId': 89,
                'isParentMenu': true,
                'icon': null,
                'children': [
                    {
                        'title': '出差申请单',
                        'type': 'menu',
                        'path': '/orderManagement/travelOrder',
                        'name': 'orderManagement_travelOrder',
                        'key': 'orderManagement_travelOrder',
                        'id': 45,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '国内机票订单',
                        'type': 'menu',
                        'path': '/orderManagement/flightOrder',
                        'name': 'orderManagement_flightOrder',
                        'key': 'orderManagement_flightOrder',
                        'id': 46,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '国际机票订单',
                        'type': 'menu',
                        'path': '/orderManagement/internationalFlightOrder',
                        'name': 'orderManagement_internationalFlightOrder',
                        'key': 'orderManagement_internationalFlightOrder',
                        'id': 130,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '火车票订单',
                        'type': 'menu',
                        'path': '/orderManagement/trainOrder',
                        'name': 'orderManagement_trainOrder',
                        'key': 'orderManagement_trainOrder',
                        'id': 47,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '酒店订单',
                        'type': 'menu',
                        'path': '/orderManagement/hotelOrder',
                        'name': 'orderManagement_hotelOrder',
                        'key': 'orderManagement_hotelOrder',
                        'id': 70,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '历史机票订单',
                        'type': 'menu',
                        'path': '/orderManagement/historyFlightOrder',
                        'name': 'history_flight_order',
                        'key': 'history_flight_order',
                        'id': 117,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '历史火车票订单',
                        'type': 'menu',
                        'path': '/orderManagement/historyTrainOrder',
                        'name': 'history_train_order',
                        'key': 'history_train_order',
                        'id': 118,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '历史酒店订单',
                        'type': 'menu',
                        'path': '/orderManagement/historyHotelOrder',
                        'name': 'history_hotel_order',
                        'key': 'history_hotel_order',
                        'id': 119,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                ],
            },
            {
                'title': '企业订单管理',
                'type': 'subMenu',
                'path': '',
                'name': 'pcCompanyOrderManager',
                'key': 'pcCompanyOrderManager',
                'id': 91,
                'parentId': 89,
                'isParentMenu': true,
                'icon': null,
                'children': [
                    {
                        'title': '国内机票订单',
                        'type': 'menu',
                        'path': '/pcCompanyOrderManager/flight',
                        'name': 'pcCompanyOrderManager_flight',
                        'key': 'pcCompanyOrderManager_flight',
                        'id': 119,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '国际机票订单',
                        'type': 'menu',
                        'path': '/pcCompanyOrderManager/interFlight',
                        'name': 'pcCompanyOrderManager_interFlight',
                        'key': 'pcCompanyOrderManager_interFlight',
                        'id': 119,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '火车票订单',
                        'type': 'menu',
                        'path': '/pcCompanyOrderManager/train',
                        'name': 'pcCompanyOrderManager_train',
                        'key': 'pcCompanyOrderManager_train',
                        'id': 119,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '酒店订单',
                        'type': 'menu',
                        'path': '/pcCompanyOrderManager/hotel',
                        'name': 'pcCompanyOrderManager_hotel',
                        'key': 'pcCompanyOrderManager_hotel',
                        'id': 119,
                        'parentId': 90,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                ],
            },
            {
                'title': '国际机票需求单',
                'type': 'menu',
                'path': '/internationalFlight/demandList',
                'name': 'internationalFlight_demandList',
                'key': 'internationalFlight_demandList',
                'id': 104,
                'parentId': 89,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '订单监控',
                'type': 'menu',
                'path': '/orderMonitor/list',
                'name': 'orderMonitor_list',
                'key': 'orderMonitor_list',
                'id': 55,
                'parentId': 89,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
        ],
    },
    {
        'title': '酒店管理',
        'type': 'subMenu',
        'path': '',
        'name': 'hotelManage',
        'key': 'hotelManage',
        'id': 111,
        'parentId': 0,
        'isParentMenu': true,
        'icon': 'hotelmanage',
        'children': [
            {
                'title': '酒店运营管理',
                'type': 'menu',
                'path': '/hotelManage/operationManage',
                'name': 'hotel_operation_manage',
                'key': 'hotel_operation_manage',
                'id': 112,
                'parentId': 111,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '酒店合并',
                'type': 'subMenu',
                'path': '',
                'name': 'hotelCombine',
                'key': 'hotelCombine',
                'id': 113,
                'parentId': 111,
                'isParentMenu': true,
                'icon': null,
                'children': [
                    {
                        'title': '待合并',
                        'type': 'menu',
                        'path': '/hotelManage/combine/wait',
                        'name': 'hotelCombine_wait',
                        'key': 'hotelCombine_wait',
                        'id': 114,
                        'parentId': 113,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '合并结果',
                        'type': 'menu',
                        'path': '/hotelManage/combine/result',
                        'name': 'hotelCombine_result',
                        'key': 'hotelCombine_result',
                        'id': 115,
                        'parentId': 113,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                ],
            },
        ],
    },
    {
        'title': '数据统计',
        'type': 'subMenu',
        'path': '',
        'name': 'dataAnalysis',
        'key': 'dataAnalysis',
        'id': 91,
        'parentId': 0,
        'isParentMenu': true,
        'icon': 'DataAnalysis',
        'children': [
            {
                'title': '报表下载',
                'type': 'subMenu',
                'path': '',
                'name': 'bgReportDownload',
                'key': 'bgReportDownload',
                'id': 92,
                'parentId': 91,
                'isParentMenu': true,
                'icon': null,
                'children': [
                    {
                        'title': '机票报表',
                        'type': 'menu',
                        'path': '/bgReportDownload/flight',
                        'name': 'bgReportDownload_flight',
                        'key': 'bgReportDownload_flight',
                        'id': 60,
                        'parentId': 92,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '酒店报表',
                        'type': 'menu',
                        'path': '/bgReportDownload/hotel',
                        'name': 'bgReportDownload_hotel',
                        'key': 'bgReportDownload_hotel',
                        'id': 66,
                        'parentId': 92,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '火车票报表',
                        'type': 'menu',
                        'path': '/bgReportDownload/train',
                        'name': 'bgReportDownload_train',
                        'key': 'bgReportDownload_train',
                        'id': 61,
                        'parentId': 92,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                ],
            },
            {
                'title': '企业统计分析',
                'type': 'subMenu',
                'path': '',
                'name': 'orderAnalysis',
                'key': 'orderAnalysis',
                'id': 107,
                'parentId': 91,
                'isParentMenu': true,
                'icon': null,
                'children': [
                    {
                        'title': '总概',
                        'type': 'menu',
                        'path': '/orderAnalysis/orderGeneral',
                        'name': 'orderAnalysis_orderGeneral',
                        'key': 'orderAnalysis_orderGeneral',
                        'id': 38,
                        'parentId': 107,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '机票分析',
                        'type': 'menu',
                        'path': '',
                        'name': 'orderAnalysis_flight',
                        'key': 'orderAnalysis_flight',
                        'id': 121,
                        'parentId': 107,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '酒店分析',
                        'type': 'menu',
                        'path': '',
                        'name': 'orderAnalysis_hotel',
                        'key': 'orderAnalysis_hotel',
                        'id': 122,
                        'parentId': 107,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '火车票分析',
                        'type': 'menu',
                        'path': '',
                        'name': 'orderAnalysis_train',
                        'key': 'orderAnalysis_train',
                        'id': 123,
                        'parentId': 107,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                ],
            },
            {
                'title': '平台统计分析',
                'type': 'subMenu',
                'path': '',
                'name': 'bg_orderAnalysis',
                'key': 'bg_orderAnalysis',
                'id': 120,
                'parentId': 91,
                'isParentMenu': true,
                'icon': null,
                'children': [
                    {
                        'title': '总概',
                        'type': 'menu',
                        'path': '',
                        'name': 'bg_orderAnalysis_orderGeneral',
                        'key': 'bg_orderAnalysis_orderGeneral',
                        'id': 124,
                        'parentId': 120,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '机票分析',
                        'type': 'menu',
                        'path': '',
                        'name': 'bg_orderAnalysis_flight',
                        'key': 'bg_orderAnalysis_flight',
                        'id': 125,
                        'parentId': 120,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '酒店分析',
                        'type': 'menu',
                        'path': '',
                        'name': 'bg_orderAnalysis_hotel',
                        'key': 'bg_orderAnalysis_hotel',
                        'id': 126,
                        'parentId': 120,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '火车票分析',
                        'type': 'menu',
                        'path': '',
                        'name': 'bg_orderAnalysis_train',
                        'key': 'bg_orderAnalysis_train',
                        'id': 127,
                        'parentId': 120,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': '平台数据',
                        'type': 'menu',
                        'path': '',
                        'name': 'bg_platform_data',
                        'key': 'bg_platform_data',
                        'id': 128,
                        'parentId': 120,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                    {
                        'title': 'TMC评分',
                        'type': 'menu',
                        'path': '',
                        'name': 'bg_TMC_score',
                        'key': 'bg_TMC_score',
                        'id': 129,
                        'parentId': 120,
                        'isParentMenu': false,
                        'icon': null,
                        'children': null,
                    },
                ],
            },
        ],
    },
    {
        'title': '基础数据',
        'type': 'subMenu',
        'path': '',
        'name': 'basicData',
        'key': 'basicData',
        'id': 93,
        'parentId': 0,
        'isParentMenu': true,
        'icon': 'baseInfo',
        'children': [
            {
                'title': '航空公司',
                'type': 'menu',
                'path': '/basicInfo/flightList',
                'name': 'basicInfo_flightList',
                'key': 'basicInfo_flightList',
                'id': 49,
                'parentId': 93,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '机场三字码',
                'type': 'menu',
                'path': '/basicInfo/airport',
                'name': 'basicInfo_airport',
                'key': 'basicInfo_airport',
                'id': 50,
                'parentId': 93,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '里程数',
                'type': 'menu',
                'path': '/basicInfo/mileage',
                'name': 'basicInfo_mileage',
                'key': 'basicInfo_mileage',
                'id': 53,
                'parentId': 93,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '火车站信息表',
                'type': 'menu',
                'path': '/basicInfo/train',
                'name': 'basicInfo_train',
                'key': 'basicInfo_train',
                'id': 51,
                'parentId': 93,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
            {
                'title': '酒店城市表',
                'type': 'menu',
                'path': '/basicInfo/hotel',
                'name': 'basicInfo_hotel',
                'key': 'basicInfo_hotel',
                'id': 52,
                'parentId': 93,
                'isParentMenu': false,
                'icon': null,
                'children': null,
            },
        ],
    },
];
